stages:
  - building

building:
  tags:
    - hugo
  image: registry.gitlab.com/pages/hugo/hugo_extended:latest
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  stage: building
  script:
    - hugo
    - touch public/timestamp
    - date +%s public/timestamp
  artifacts:
    paths:
      - public
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
