# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
de:
  languageCode: de
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/de
# Uncomment the lines below to configure your website in a second language.
en:
  contentDir: content/en
  title: DROPS Research Project
  params:
    description: The DROPS Research Project

