baseURL = "https://itsec.cs.uni-bonn.de/drops"
languageCode = "de-DE"
title = "DROPS"
theme = "hugo-hero-theme"

[params]
  logo = "/images/logo.png"

  [params.homepage_meta_tags]
    meta_description = "Forschungsprojekt DROPS - Datentreuhand-Modul zum Präventivenschutz vor Identitätsdatenmissbrauch"
    meta_og_title = "DROPS"
    meta_og_type = "website"
    meta_og_url = "https://itsec.cs.uni-bonn.de/drops"
    meta_og_image = "https://itsec.cs.uni-bonn.de/drops/favicon.png"
    meta_og_description = "Forschungsprojekt DROPS - Datentreuhand-Modul zum Präventivenschutz vor Identitätsdatenmissbrauch"


[[menu.main]]
    name = "Startseite"
    url = "/"
    weight = 3


#[[menu.main]]
#    name = "Veröffentlichungen"
#    url = "/#publikationen"
#    weight = 3

[[menu.main]]
    name = "Kontakt"
    url = "/#kontakt"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"

[blackfriday]
extensions = ["hardLineBreak"]
